FROM jenkins/jenkins:lts

USER root

# ติดตั้ง Docker CLI และ Docker Compose plugin
RUN curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-27.3.1.tgz \
    && tar xzvf docker-27.3.1.tgz \
    && mv docker/docker /usr/local/bin/ \
    && mkdir -p /usr/local/lib/docker/cli-plugins \
    && curl -SL https://github.com/docker/compose/releases/download/v2.29.1/docker-compose-linux-x86_64 \
    -o /usr/local/lib/docker/cli-plugins/docker-compose \
    && chmod +x /usr/local/lib/docker/cli-plugins/docker-compose \
    && rm -rf docker docker-27.3.1.tgz

USER jenkins
