server {
    listen 80;
    index index.php index.html;
    root /var/www/public;

    # สำหรับจัดการเส้นทางของ Laravel (URL Routing)
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # สำหรับผูกกับ PHP-FPM Container
    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
